name: Unzip File

on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Unzip file
        run: unzip ziti/zhuzi-font.zip -d ziti/unzipped-fonts

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ziti/unzipped-fonts
          git commit -m 'Unzipped zhuzi-font.zip'
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/你的用户名/你的仓库名.git HEAD:main
