# 将静态内容部署到 GitHub Pages 的简单工作流程
name: Deploy static content to Pages

 关于:
# 运行针对默认分支的推送
推:
分支:["main"]

# 允许您从 “操作” 选项卡手动运行此工作流
 workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，允许部署到 GitHub Pages
 权限:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过正在进行中的运行和最新排队之间排队的运行。
# 但是，不要取消正在进行中的运行，因为我们希望允许这些生产部署完成。
 并发:
  group: "pages"
  cancel-in-progress: false

 工作:
# 单部署作业，因为我们只是部署
部署:
 环境:
      name: github-pages
 url: ${{ steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
 步骤:
                                             - 名称:结账
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
 使用 :  actions/upload-pages-artifact@v3
 与:
# 上传整个存储库
道:'。
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
